import { MetaInfo } from 'vue-meta'

interface MyMetaInfo {
    title?: string,
    content?: string,
    image?: string,
    url?: string,
    type?: string

}

export class General {

    pasteAsPlainText (e: ClipboardEvent) {
        // e.preventDefault()
        // let t = e.target as any
        // if (t.tagName === 'BR')
        //     // t += e.clipboardData.getData('text/plain')
        //     t.closest('div').textContent += e.clipboardData.getData('text/plain')
        // else
        //     t.textContent += e.clipboardData.getData('text/plain')
        // console.log('jjjjjj', t)

    }

    appLogo (cssClasses: string /* provide the respective css class to decide how the logo is displayed */) {
        return `
        <div class="logo-base ${cssClasses ? cssClasses : 'logo-trans-1 shadow-2'}">
            <span>
                <span></span>
                <span></span>
            </span>
            <span></span>
        </div>
    `
    }
    /* vue-meta abstraction method */
    metaInfo (data: MyMetaInfo) {
        const defaults = {
            title: 'scavorb - websites and web app development',
            content: "scavorb - websites and web apps development for artists and designers. Have your personal and business website's UI professionally designed for the best user experience and satisfaction.",
            image: 'https://www.scavorb.com/defaults/pgs/scavorb_website_design_and_development.jpg',
            url: '',
            type: 'website'
        }


        return {
            title: data.title || defaults.title,
            meta: [
                {
                    name: 'description',
                    content: data.content ? data.content.slice(0, 250) + '...' : defaults.content
                },
                {
                    property: 'og:title',
                    content: data.title || defaults.title
                },
                {
                    property: 'og:description',
                    content: data.content ? data.content.slice(0, 250) + '...' : defaults.content
                },
                {
                    property: 'og:url',
                    content: data.url || defaults.url
                },
                {
                    property: 'og:image',/* reccomended aspect-ratio 1200x630 */
                    content: data.image || defaults.image
                },
                {
                    property: 'og:type',
                    content: data.type || defaults.type
                },
                {
                    name: 'robots',
                    content: 'index, follow'
                }
            ]
        }
    }

    countries () {
        return [
            "&#197;land Islands",
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctica",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belau",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bonaire, Saint Eustatius and Saba",
            "Bosnia and Herzegovina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory",
            "British Virgin Islands",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands",
            "Colombia",
            "Comoros",
            "Congo (Brazzaville)",
            "Congo (Kinshasa)",
            "Cook Islands",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cura&ccedil;ao",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Falkland Islands",
            "Faroe Islands",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "French Southern Territories",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard Island and McDonald Islands",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Ivory Coast",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao S.A.R., China",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "North Korea",
            "Northern Mariana Islands",
            "Norway",
            "Oman",
            "Pakistan",
            "Palestinian Territory",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Pitcairn",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Reunion",
            "Romania",
            "Russia",
            "Rwanda",
            "S&atilde;o Tom&eacute; and Pr&iacute;ncipe",
            "Saint Barth&eacute;lemy",
            "Saint Helena",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Martin (Dutch part)",
            "Saint Martin (French part)",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Georgia/Sandwich Islands",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Svalbard and Jan Mayen",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom (UK)",
            "United States (US)",
            "United States (US) Minor Outlying Islands",
            "United States (US) Virgin Islands",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican",
            "Venezuela",
            "Vietnam",
            "Wallis and Futuna",
            "Western Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe"

        ]
        // return {
        //     "AX": "&#197;land Islands",
        //     "AF": "Afghanistan",
        //     "AL": "Albania",
        //     "DZ": "Algeria",
        //     "AS": "American Samoa",
        //     "AD": "Andorra",
        //     "AO": "Angola",
        //     "AI": "Anguilla",
        //     "AQ": "Antarctica",
        //     "AG": "Antigua and Barbuda",
        //     "AR": "Argentina",
        //     "AM": "Armenia",
        //     "AW": "Aruba",
        //     "AU": "Australia",
        //     "AT": "Austria",
        //     "AZ": "Azerbaijan",
        //     "BS": "Bahamas",
        //     "BH": "Bahrain",
        //     "BD": "Bangladesh",
        //     "BB": "Barbados",
        //     "BY": "Belarus",
        //     "PW": "Belau",
        //     "BE": "Belgium",
        //     "BZ": "Belize",
        //     "BJ": "Benin",
        //     "BM": "Bermuda",
        //     "BT": "Bhutan",
        //     "BO": "Bolivia",
        //     "BQ": "Bonaire, Saint Eustatius and Saba",
        //     "BA": "Bosnia and Herzegovina",
        //     "BW": "Botswana",
        //     "BV": "Bouvet Island",
        //     "BR": "Brazil",
        //     "IO": "British Indian Ocean Territory",
        //     "VG": "British Virgin Islands",
        //     "BN": "Brunei",
        //     "BG": "Bulgaria",
        //     "BF": "Burkina Faso",
        //     "BI": "Burundi",
        //     "KH": "Cambodia",
        //     "CM": "Cameroon",
        //     "CA": "Canada",
        //     "CV": "Cape Verde",
        //     "KY": "Cayman Islands",
        //     "CF": "Central African Republic",
        //     "TD": "Chad",
        //     "CL": "Chile",
        //     "CN": "China",
        //     "CX": "Christmas Island",
        //     "CC": "Cocos (Keeling) Islands",
        //     "CO": "Colombia",
        //     "KM": "Comoros",
        //     "CG": "Congo (Brazzaville)",
        //     "CD": "Congo (Kinshasa)",
        //     "CK": "Cook Islands",
        //     "CR": "Costa Rica",
        //     "HR": "Croatia",
        //     "CU": "Cuba",
        //     "CW": "Cura&ccedil;ao",
        //     "CY": "Cyprus",
        //     "CZ": "Czech Republic",
        //     "DK": "Denmark",
        //     "DJ": "Djibouti",
        //     "DM": "Dominica",
        //     "DO": "Dominican Republic",
        //     "EC": "Ecuador",
        //     "EG": "Egypt",
        //     "SV": "El Salvador",
        //     "GQ": "Equatorial Guinea",
        //     "ER": "Eritrea",
        //     "EE": "Estonia",
        //     "ET": "Ethiopia",
        //     "FK": "Falkland Islands",
        //     "FO": "Faroe Islands",
        //     "FJ": "Fiji",
        //     "FI": "Finland",
        //     "FR": "France",
        //     "GF": "French Guiana",
        //     "PF": "French Polynesia",
        //     "TF": "French Southern Territories",
        //     "GA": "Gabon",
        //     "GM": "Gambia",
        //     "GE": "Georgia",
        //     "DE": "Germany",
        //     "GH": "Ghana",
        //     "GI": "Gibraltar",
        //     "GR": "Greece",
        //     "GL": "Greenland",
        //     "GD": "Grenada",
        //     "GP": "Guadeloupe",
        //     "GU": "Guam",
        //     "GT": "Guatemala",
        //     "GG": "Guernsey",
        //     "GN": "Guinea",
        //     "GW": "Guinea-Bissau",
        //     "GY": "Guyana",
        //     "HT": "Haiti",
        //     "HM": "Heard Island and McDonald Islands",
        //     "HN": "Honduras",
        //     "HK": "Hong Kong",
        //     "HU": "Hungary",
        //     "IS": "Iceland",
        //     "IN": "India",
        //     "ID": "Indonesia",
        //     "IR": "Iran",
        //     "IQ": "Iraq",
        //     "IE": "Ireland",
        //     "IM": "Isle of Man",
        //     "IL": "Israel",
        //     "IT": "Italy",
        //     "CI": "Ivory Coast",
        //     "JM": "Jamaica",
        //     "JP": "Japan",
        //     "JE": "Jersey",
        //     "JO": "Jordan",
        //     "KZ": "Kazakhstan",
        //     "KE": "Kenya",
        //     "KI": "Kiribati",
        //     "KW": "Kuwait",
        //     "KG": "Kyrgyzstan",
        //     "LA": "Laos",
        //     "LV": "Latvia",
        //     "LB": "Lebanon",
        //     "LS": "Lesotho",
        //     "LR": "Liberia",
        //     "LY": "Libya",
        //     "LI": "Liechtenstein",
        //     "LT": "Lithuania",
        //     "LU": "Luxembourg",
        //     "MO": "Macao S.A.R., China",
        //     "MK": "Macedonia",
        //     "MG": "Madagascar",
        //     "MW": "Malawi",
        //     "MY": "Malaysia",
        //     "MV": "Maldives",
        //     "ML": "Mali",
        //     "MT": "Malta",
        //     "MH": "Marshall Islands",
        //     "MQ": "Martinique",
        //     "MR": "Mauritania",
        //     "MU": "Mauritius",
        //     "YT": "Mayotte",
        //     "MX": "Mexico",
        //     "FM": "Micronesia",
        //     "MD": "Moldova",
        //     "MC": "Monaco",
        //     "MN": "Mongolia",
        //     "ME": "Montenegro",
        //     "MS": "Montserrat",
        //     "MA": "Morocco",
        //     "MZ": "Mozambique",
        //     "MM": "Myanmar",
        //     "NA": "Namibia",
        //     "NR": "Nauru",
        //     "NP": "Nepal",
        //     "NL": "Netherlands",
        //     "NC": "New Caledonia",
        //     "NZ": "New Zealand",
        //     "NI": "Nicaragua",
        //     "NE": "Niger",
        //     "NG": "Nigeria",
        //     "NU": "Niue",
        //     "NF": "Norfolk Island",
        //     "KP": "North Korea",
        //     "MP": "Northern Mariana Islands",
        //     "NO": "Norway",
        //     "OM": "Oman",
        //     "PK": "Pakistan",
        //     "PS": "Palestinian Territory",
        //     "PA": "Panama",
        //     "PG": "Papua New Guinea",
        //     "PY": "Paraguay",
        //     "PE": "Peru",
        //     "PH": "Philippines",
        //     "PN": "Pitcairn",
        //     "PL": "Poland",
        //     "PT": "Portugal",
        //     "PR": "Puerto Rico",
        //     "QA": "Qatar",
        //     "RE": "Reunion",
        //     "RO": "Romania",
        //     "RU": "Russia",
        //     "RW": "Rwanda",
        //     "ST": "S&atilde;o Tom&eacute; and Pr&iacute;ncipe",
        //     "BL": "Saint Barth&eacute;lemy",
        //     "SH": "Saint Helena",
        //     "KN": "Saint Kitts and Nevis",
        //     "LC": "Saint Lucia",
        //     "SX": "Saint Martin (Dutch part)",
        //     "MF": "Saint Martin (French part)",
        //     "PM": "Saint Pierre and Miquelon",
        //     "VC": "Saint Vincent and the Grenadines",
        //     "WS": "Samoa",
        //     "SM": "San Marino",
        //     "SA": "Saudi Arabia",
        //     "SN": "Senegal",
        //     "RS": "Serbia",
        //     "SC": "Seychelles",
        //     "SL": "Sierra Leone",
        //     "SG": "Singapore",
        //     "SK": "Slovakia",
        //     "SI": "Slovenia",
        //     "SB": "Solomon Islands",
        //     "SO": "Somalia",
        //     "ZA": "South Africa",
        //     "GS": "South Georgia/Sandwich Islands",
        //     "KR": "South Korea",
        //     "SS": "South Sudan",
        //     "ES": "Spain",
        //     "LK": "Sri Lanka",
        //     "SD": "Sudan",
        //     "SR": "Suriname",
        //     "SJ": "Svalbard and Jan Mayen",
        //     "SZ": "Swaziland",
        //     "SE": "Sweden",
        //     "CH": "Switzerland",
        //     "SY": "Syria",
        //     "TW": "Taiwan",
        //     "TJ": "Tajikistan",
        //     "TZ": "Tanzania",
        //     "TH": "Thailand",
        //     "TL": "Timor-Leste",
        //     "TG": "Togo",
        //     "TK": "Tokelau",
        //     "TO": "Tonga",
        //     "TT": "Trinidad and Tobago",
        //     "TN": "Tunisia",
        //     "TR": "Turkey",
        //     "TM": "Turkmenistan",
        //     "TC": "Turks and Caicos Islands",
        //     "TV": "Tuvalu",
        //     "UG": "Uganda",
        //     "UA": "Ukraine",
        //     "AE": "United Arab Emirates",
        //     "GB": "United Kingdom (UK)",
        //     "US": "United States (US)",
        //     "UM": "United States (US) Minor Outlying Islands",
        //     "VI": "United States (US) Virgin Islands",
        //     "UY": "Uruguay",
        //     "UZ": "Uzbekistan",
        //     "VU": "Vanuatu",
        //     "VA": "Vatican",
        //     "VE": "Venezuela",
        //     "VN": "Vietnam",
        //     "WF": "Wallis and Futuna",
        //     "EH": "Western Sahara",
        //     "YE": "Yemen",
        //     "ZM": "Zambia",
        //     "ZW": "Zimbabwe"

        // }
    }
}
